#!/bin/bash

menu_src () {
bot_retorno="=========COMANDOS=========\n"
	 if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 bot_retorno+="/ID (muestra sus ID)\n"
		 bot_retorno+="/menu (muestra este menu)\n"
		 bot_retorno+="/ayuda (muestra ayuda de los comandos)\n"
		 bot_retorno+="$LINE\n"
	 else		 
		 bot_retorno+="/infosys (informacion del sistema)\n"
		 bot_retorno+="/ID (muestra sus ID)\n"
		 bot_retorno+="/menu (muestra este menu)\n"
		 bot_retorno+="/ayuda (muestra ayuda de los comandos)\n"
		 bot_retorno+="/cache (Limpiar cache Ram)\n"
		 bot_retorno+="/update (actualiza el BotGen)\n"
		 bot_retorno+="/reboot (Reinicia el servidor vps)\n"
		 bot_retorno+="$LINE\n"
	 fi	
msj_fun
}
